### ISSUE TITLE
Create CONTRIBUTING.md file

### ISSUE THREAD

**Issue by tiagostutz** [lwsjs/lws#14]
As I'm working on the issue #13 I'm writing here a first version CONTRIBUTING.md guidelines, using as references:
- https://www.contributor-covenant.org/pt-br/version/1/4/code-of-conduct/
- https://github.com/atom/atom/blob/master/CONTRIBUTING.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question
- https://reactjs.org/docs/how-to-contribute.html

Is that ok?

**Comment by tiagostutz** [comment]
I'm also thinking about referencing https://www.conventionalcommits.org/ as a good practice for code commiting, but not mandatory.

**Comment by 75lb** [comment]
I'll write a quick contribution guideline now.. I'm at work (like you) so will do more work on this tonight..

**Comment by 75lb** [comment]
[first draft](https://github.com/lwsjs/lws/blob/master/CONTRIBUTING.md)

**Comment by tiagostutz** [comment]
That's pPerfect, thanks!

**Comment by tiagostutz** [comment]
I can write a "Development Workflow" session on the CONTRIBUTING file as I'm going to the step-by-step of cloning, installing, coding, testing, covering, etc.

What do you think?

**Comment by 75lb** [comment]
For things like developer/contributor notes, files that change often and don't directly affect the codebase, I think a Wiki page is better suited.. Wiki pages are good because people can quickly edit and fix them without the usual PR process. 

I created a placeholder on the [wiki home page](https://github.com/lwsjs/lws/wiki) for you to link to a Development Workflow document. 👍

**Comment by tiagostutz** [comment]
Yeah, you are right. I agree.

Thanks for the tip.!
