### ISSUE TITLE
SSL certificates expired

### ISSUE THREAD

**Issue by radum** [lwsjs/lws#5]
I think the SSL certificate that gets bundled here has already expired.

So using --https won't work anymore on Chrome for example.

**Comment by 75lb** [comment]
ahh, yes - thanks for reminding me! Will fix that ASAP with a new cert with longer expiry time.. watch this space..

**Comment by 75lb** [comment]
Fixed in lws v1.1.3 and local-web-server v2.2.3. You may need to [mark the new certificate as trusted](https://github.com/lwsjs/local-web-server/wiki/How-to-get-the-%22green-padlock%22-using-the-built-in-certificate#trust-the-certificate-macos), sorry about that. 

Let me know if you find anything else 👍
